/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

//public void departmentListClicked(GDropList source, GEvent event) { //_CODE_:department:782519:
//  String departmentType ;
//  departmentType = department.getSelectedText();
//  if (departmentType == "Dairy");
//    milkButton.setVisible(true);
//    yogurtButton.setVisible(false);
  
//} //_CODE_:department:782519:

public void milkButtonClicked(GButton source, GEvent event) { //_CODE_:milkButton:597819:
  
  Item item1 = new Item("Milk",10, 9, 1, 5.50);
  items = (Item[]) append(items,item1);
  DestinationSet = true;
  ItemNum += 1;
  item1.amt = item1.amt + 1;
  cart.add(item1.name);
} //_CODE_:milkButton:597819:

public void YogurtButtonClicked(GButton source, GEvent event) { //_CODE_:yogurtButton:304453:
 
  Item item2 = new Item("Yogurt",4, 9, 1, 3.40);
  items = (Item[]) append(items,item2);
  DestinationSet = true;
  ItemNum += 1;
  item2.amt = item2.amt + 1;
  cart.add(item2.name);
  
} //_CODE_:yogurtButton:304453:

public void chickenButtonClicked(GButton source, GEvent event) { //_CODE_:chickenButton:398522:

  Item item3 = new Item("Chicken",8, 5, 1, 14.99);
  items = (Item[]) append(items,item3);
  DestinationSet = true;
  ItemNum += 1;
  item3.amt = item3.amt + 1;
  cart.add(item3.name);
} //_CODE_:chickenButton:398522:

public void tomatoSButtonClicked(GButton source, GEvent event) { //_CODE_:tomatoSButton:391332:

  Item item4 = new Item("Tomato",3, 3, 1, 8.89);
  items = (Item[]) append(items,item4);
  DestinationSet = true;
  ItemNum += 1;
  item4.amt = item4.amt + 1;
  cart.add(item4.name);
} //_CODE_:tomatoSButton:391332:

public void soupCButtonClicked(GButton source, GEvent event) { //_CODE_:soupC:662700:

  Item item5 = new Item("Soup",8, 4, 1, 4.00);
  items = (Item[]) append(items,item5);
  DestinationSet = true;
  ItemNum += 1;
  item5.amt = item5.amt + 1;
  cart.add(item5.name);
} //_CODE_:soupC:662700:

public void BeefButtonClicked(GButton source, GEvent event) { //_CODE_:beefButton:671859:

  Item item6 = new Item("Beef",8, 3, 1, 13.00);
  items = (Item[]) append(items,item6);
  DestinationSet = true;
  ItemNum += 1;
  item6.amt = item6.amt + 1;
  cart.add(item6.name);
} //_CODE_:beefButton:671859:

public void crackersButtonClicked(GButton source, GEvent event) { //_CODE_:CrackersButton:788604:

  Item item7 = new Item("Crackers",8, 6, 1, 2.00);
  items = (Item[]) append(items,item7);
  DestinationSet = true;
  ItemNum += 1;
  item7.amt = item7.amt + 1;
  cart.add(item7.name);
} //_CODE_:CrackersButton:788604:

public void WBreadButtonClicked(GButton source, GEvent event) { //_CODE_:wBreadButton:588538:

  Item item8 = new Item("White Bread",3, 5, 1, 4.49);
  items = (Item[]) append(items,item8);
  DestinationSet = true;
  ItemNum += 1;
  item8.amt = item8.amt + 1;
  cart.add(item8.name);
} //_CODE_:wBreadButton:588538:

public void doneButtonClicked(GButton source, GEvent event) { //_CODE_:doneButton:785750:
  done = true; 
  goToBool = true;
  count = 0;
} //_CODE_:doneButton:785750:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:744998:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:744998:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:529947:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:529947:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:312841:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:312841:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 150, 12, 100, 27);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("PATHAWAYS");
  label1.setOpaque(false);
  department = new GDropList(this, 29, 51, 111, 132, 5, 10);
  department.setItems(loadStrings("list_782519"), 0);
  department.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  department.addEventHandler(this, "departmentListClicked");
  togGroup1 = new GToggleGroup();
  label2 = new GLabel(this, 31, 27, 80, 29);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("My budget is:");
  label2.setOpaque(false);
  milkButton = new GButton(this, 20, 141, 80, 30);
  milkButton.setText("Milk");
  milkButton.addEventHandler(this, "milkButtonClicked");
  yogurtButton = new GButton(this, 20, 201, 80, 30);
  yogurtButton.setText("Yogurt");
  yogurtButton.addEventHandler(this, "YogurtButtonClicked");
  chickenButton = new GButton(this, 210, 202, 80, 30);
  chickenButton.setText("Chicken");
  chickenButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  chickenButton.addEventHandler(this, "chickenButtonClicked");
  tomatoSButton = new GButton(this, 300, 201, 80, 30);
  tomatoSButton.setText("Tomato Sauce");
  tomatoSButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  tomatoSButton.addEventHandler(this, "tomatoSButtonClicked");
  soupC = new GButton(this, 300, 140, 80, 30);
  soupC.setText("Soup can");
  soupC.setLocalColorScheme(GCScheme.RED_SCHEME);
  soupC.addEventHandler(this, "soupCButtonClicked");
  beefButton = new GButton(this, 210, 141, 80, 30);
  beefButton.setText("Beef");
  beefButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  beefButton.addEventHandler(this, "BeefButtonClicked");
  CrackersButton = new GButton(this, 115, 201, 80, 30);
  CrackersButton.setText("Crackers");
  CrackersButton.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  CrackersButton.addEventHandler(this, "crackersButtonClicked");
  wBreadButton = new GButton(this, 115, 141, 80, 30);
  //wBreadButton.setTextAlign(GAlign.GOLD_SCHEME, GAlign.MIDDLE);
  wBreadButton.setText("White Bread ");
  wBreadButton.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  wBreadButton.addEventHandler(this, "WBreadButtonClicked");
  doneButton = new GButton(this, 160, 271, 80, 30);
  doneButton.setText("Done");
  doneButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  doneButton.addEventHandler(this, "doneButtonClicked");
  button1 = new GButton(this, 40, 350, 80, 30);
  button1.setText("Broke Student");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 160, 350, 80, 30);
  button2.setText("Big family");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 280, 350, 80, 30);
  button3.setText("Rich couple");
  button3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  label3 = new GLabel(this, 160, 324, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Demos:");
  label3.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GDropList department; 
GToggleGroup togGroup1; 
GLabel label2; 
GButton milkButton; 
GButton yogurtButton; 
GButton chickenButton; 
GButton tomatoSButton; 
GButton soupC; 
GButton beefButton; 
GButton CrackersButton; 
GButton wBreadButton; 
GButton doneButton; 
GButton button1; 
GButton button2; 
GButton button3; 
GLabel label3; 
