/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:869930:
  appc.background(230);
} //_CODE_:window1:869930:

public void milk_click(GButton source, GEvent event) { //_CODE_:Milk:839104:
  //println("Milk - GButton >> GEvent." + event + " @ " + millis());
  Item item1 = new Item("Milk",17, 6);
  items = (Item[]) append(items,item1);
  DestinationSet = true;
  ItemNum += 1;
  
} //_CODE_:Milk:839104:

public void eggs_click(GButton source, GEvent event) { //_CODE_:eggs:740270:
  //println("eggs - GButton >> GEvent." + event + " @ " + millis());
  Item item2 = new Item("Eggs", 17, 12); 
  items = (Item[]) append(items,item2);
  DestinationSet = true;
  ItemNum += 1;
} //_CODE_:eggs:740270:

public void bread_click(GButton source, GEvent event) { //_CODE_:Bread:804874:
  println("Bread - GButton >> GEvent." + event + " @ " + millis());
  Item item3 = new Item("Bread",11, 10);
  items = (Item[]) append(items,item3);
  DestinationSet = true;
  ItemNum += 1;
} //_CODE_:Bread:804874:

public void apple_click(GButton source, GEvent event) { //_CODE_:Apple:970061:
  println("Apple - GButton >> GEvent." + event + " @ " + millis());
  Item item4 = new Item("Apple",5, 13);
  items = (Item[]) append(items,item4);
  DestinationSet = true;
  ItemNum += 1;
} //_CODE_:Apple:970061:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Milk = new GButton(window1, 10, 13, 80, 30);
  Milk.setText("Milk");
  Milk.addEventHandler(this, "milk_click");
  eggs = new GButton(window1, 123, 13, 80, 30);
  eggs.setText("Eggs");
  eggs.addEventHandler(this, "eggs_click");
  Bread = new GButton(window1, 10, 62, 80, 30);
  Bread.setText("Bread");
  Bread.addEventHandler(this, "bread_click");
  Apple = new GButton(window1, 123, 62, 80, 30);
  Apple.setText("Apple");
  Apple.addEventHandler(this, "apple_click");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton Milk; 
GButton eggs; 
GButton Bread; 
GButton Apple; 
